version: '2.4'

services:
  node:
    image: rayproject/ray:1.2.0
    shm_size: '3gb'
    ports:
    - 8265:8265
    - 6379:6379
    command: ["ray",
              "start",
              "--head",
              "--block"]
